// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-V1Z5XeUzGs96bNXcra2ylb_QyXPgWmA',
    appId: '1:700652397479:web:84a7d55b7229d35e9e0c82',
    messagingSenderId: '700652397479',
    projectId: 'foodgofirebase',
    authDomain: 'foodgofirebase.firebaseapp.com',
    storageBucket: 'foodgofirebase.firebasestorage.app',
    measurementId: 'G-BPM0H20SSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXweZ7goy-5wvYybyY_m6fLD6egrsFIao',
    appId: '1:700652397479:android:884720f613f56dbf9e0c82',
    messagingSenderId: '700652397479',
    projectId: 'foodgofirebase',
    storageBucket: 'foodgofirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDbsy2aGni2VAa82KRRXycnqkrRivV2PQ',
    appId: '1:700652397479:ios:9710aeadbd85fcb19e0c82',
    messagingSenderId: '700652397479',
    projectId: 'foodgofirebase',
    storageBucket: 'foodgofirebase.firebasestorage.app',
    iosBundleId: 'com.example.foodgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDbsy2aGni2VAa82KRRXycnqkrRivV2PQ',
    appId: '1:700652397479:ios:9710aeadbd85fcb19e0c82',
    messagingSenderId: '700652397479',
    projectId: 'foodgofirebase',
    storageBucket: 'foodgofirebase.firebasestorage.app',
    iosBundleId: 'com.example.foodgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-V1Z5XeUzGs96bNXcra2ylb_QyXPgWmA',
    appId: '1:700652397479:web:588b7cc155361e1c9e0c82',
    messagingSenderId: '700652397479',
    projectId: 'foodgofirebase',
    authDomain: 'foodgofirebase.firebaseapp.com',
    storageBucket: 'foodgofirebase.firebasestorage.app',
    measurementId: 'G-38ZFQ1MGFM',
  );

}